apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-api

spec:
  replicas: 3

  template:
    spec:
      containers:
      - name: retail-api
        image: retail-api
        ports:
        - containerPort: 5000
